### ISSUE TITLE
exiting mid-questionnaire loses user responses entered without warning

### ISSUE THREAD

**Issue by laurazabsmith** [DarwinsDogs/DD_SurveyPages#4] opened 2016-08-23 15:57 UTC
begin questionnaire  
select checkbox for at least one question  
navigate away from survey (I clicked the "HOME" link on the top bar) 
start same questionnaire for same dog  
previous selections not persisted.  

questionnaire tested: Canine Eccentricities
browser: Chrome Version 52.0.2743.116 m

**Comment by DarwinsDogs** [comment] 2016-08-23 18:30
Thanks.  Can you clarify: does this happen if you enter answers for _more than one_ question?  I may want to find a way to clarify this, but as is, a question isn't submitted until you move on to the next one.  So - as far as I know - the worst case scenario when navigating away or closing a browser or a power outage, etc, is that only the one question you are currently looking at might not be saved.

If you move on to the second question the first definitely should be saved.  If this doesn't happen it's a definite bug.  If the first but not second is saved, then perhaps I could consider a new implementation, but it'd be behaving as intended.

**Comment by laurazabsmith** [comment] 2016-08-23 18:54
Yes. The first time I saw the issue I had answered the first 4 or 5 questions. After navigating away and then returning to the questionnaire, the previously entered responses for all of the questions were gone.

**Comment by laurazabsmith** [comment] 2016-08-23 18:57
Confirmed reproduced. 
Begin eccentricities questionnaire
answer first three questions (click checkbox and then click right arrow to advance to next page, 3 times) 
click HOME link in top bar
begin eccentricities questionnaire again for same dog (choosing from my two dogs) 
previously entered responses are not displayed.

**Comment by DarwinsDogs** [comment] 2016-08-25 18:43
Thanks, that's definitely a significant bug.  Unfortunately at the moment I can't replicate it.  I can confirm that no answers were submitted to the database for those questions for your dogs.  So the behavior of restarting the survey makes sense given no answers were saved.

So the bug is in submitting the answers.  This will help me dig a bit deeper.

**Comment by laurazabsmith** [comment] 2016-08-25 18:53
I tried again with the developer console open (still in chrome, version in orig comment). Appears to be an issue with https. Here's the console output from starting the eccentricities survey, advancing to the first question, clicking a checkbox for the first question, and then clicking the right arrow to advance to the second question. 
[darwinsdogs.org-1472150950894.txt](https://github.com/DarwinsDogs/DD_SurveyPages/files/437834/darwinsdogs.org-1472150950894.txt)

**Comment by DarwinsDogs** [comment] 2016-08-31 18:09
Thanks.  I started suspecting that might be what it was.  We're changing everything over to SSL (https) on the site, but it is a gradual process especially with the old survey pages (I'm really looking forward to _not_ maintaining those anymore).  During the transition time both http and https will be allowed, but this opens the door for these mixed-content errors until I get all the urls to either use the $dd_root variable or use protocol-relative urls.

I think I've eliminated all hard-coded-protocol urls in the new survey pages now - if you could retest, that'd be appreciated.

**Comment by laurazabsmith** [comment] 2016-08-31 18:23
Works now. Start survey, answer one question, click right arrow.  
Click "HOME" link, restart survey (the menu there is now labeled "resume" instead of "start" which is new) and the previous response to the question is still visible. 

There are still some errors in the dev console (console output pasted below) but the behavior seems good.  

?pg=survey&n=16&id=5025:433 Refused to set unsafe header "Content-length"post_data @ ?pg=survey&n=16&id=5025:433submit_answer @ ?pg=survey&n=16&id=5025:392show_question @ ?pg=survey&n=16&id=5025:314onclick @ ?pg=survey&n=16&id=5025:102
?pg=survey&n=16&id=5025:434 Refused to set unsafe header "Connection"post_data @ ?pg=survey&n=16&id=5025:434submit_answer @ ?pg=survey&n=16&id=5025:392show_question @ ?pg=survey&n=16&id=5025:314onclick @ ?pg=survey&n=16&id=5025:102
?pg=survey&n=16&id=5025:433 Refused to set unsafe header "Content-length"post_data @ ?pg=survey&n=16&id=5025:433submit_answer @ ?pg=survey&n=16&id=5025:396show_question @ ?pg=survey&n=16&id=5025:314onclick @ ?pg=survey&n=16&id=5025:102
?pg=survey&n=16&id=5025:434 Refused to set unsafe header "Connection"post_data @ ?pg=survey&n=16&id=5025:434submit_answer @ ?pg=survey&n=16&id=5025:396show_question @ ?pg=survey&n=16&id=5025:314onclick @ ?pg=survey&n=16&id=5025:102
?pg=survey&n=16&id=5025:442 XHR finished loading: POST "https://darwinsdogs.org/~jmcclure/draft/submit.php".post_data @ ?pg=survey&n=16&id=5025:442submit_answer @ ?pg=survey&n=16&id=5025:392show_question @ ?pg=survey&n=16&id=5025:314onclick @ ?pg=survey&n=16&id=5025:102
?pg=survey&n=16&id=5025:442 XHR finished loading: POST "https://darwinsdogs.org/~jmcclure/draft/submit.php".post_data @ ?pg=survey&n=16&id=5025:442submit_answer @ ?pg=survey&n=16&id=5025:396show_question @ ?pg=survey&n=16&id=5025:314onclick @ ?pg=survey&n=16&id=5025:102
VM168:1 Uncaught SyntaxError: Unexpected token 
 in JSON at position 46http.onreadystatechange @ ?pg=survey&n=16&id=5025:437

**Comment by DarwinsDogs** [comment] 2016-09-08 17:44
Thanks.  That content length error is a separate issue that I've been aware of.

That error is due to some ambiguity in a AJAX/AJAJ protocol specification.  It seems the specification says that header should be provided (thus I provide it) but most browsers seem to claim it is unsafe and ignore it.  But it is ignored without any harm, so I can likely remove it.  But until I learn a bit more I feel odd going against a protocol specification.

I'm closing this issue, I'll open another for the content-length header - thanks.

**Closed as completed by DarwinsDogs** 2016-09-08 17:44 UTC
Labels: bug, high priority
